services:

  postgres:
    image: postgres:16
    container_name: sports-bet-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


  db_service:
    build:
      context: .
      dockerfile: src/db_service/Dockerfile
    container_name: sports-bet-db-service
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy

  loro_scrape_service:
      build:
        context: .
        dockerfile: src/loro_scrape_service/Dockerfile
      container_name: loro-scrape-service
      environment:
        - DB_SERVICE_URL=http://db_service:8000
        - SCRAPE_FREQUENCY_HOURS=${SCRAPE_FREQUENCY_HOURS}
      depends_on:
        db_service:
          condition: service_started


  swisslos_scrape_service:
    build:
      context: .
      dockerfile: src/swisslos_scrape_service/Dockerfile
    container_name: swisslos-scrape-service
    environment:
      - DB_SERVICE_URL=http://db_service:8000
      - SCRAPE_FREQUENCY_HOURS=${SCRAPE_FREQUENCY_HOURS}
    depends_on:
      db_service:
        condition: service_started


  dashboard:
    build:
      context: .
      dockerfile: src/dashboard/Dockerfile
    container_name: sports-bet-dashboard
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - DB_SERVICE_URL=http://db_service:8000
    depends_on:
      db_service:
        condition: service_started
    restart: unless-stopped



volumes:
  postgres_data:
