"""initial schema

Revision ID: 7953ea54e96c
Revises:
Create Date: 2026-09-10 23:56:36.980363

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7953ea54e96c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("match_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_datetime", sa.DateTime(), nullable=False),
        sa.Column("team1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_label", "match_datetime"),
    )
    op.create_table(
        "bookmakermatch",
        sa.Column("bookmaker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_datetime", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("matching_attempts", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bookmaker", "match_label", "match_datetime"),
    )
    with op.batch_alter_table("bookmakermatch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bookmakermatch_matching_attempts"),
            ["matching_attempts"],
            unique=False,
        )

    op.create_table(
        "sportsbettingodds",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("team1_odds", sa.Float(), nullable=False),
        sa.Column("draw_odds", sa.Float(), nullable=True),
        sa.Column("team2_odds", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_match_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookmaker_match_id"],
            ["bookmakermatch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sportsbettingodds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sportsbettingodds_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sportsbettingodds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sportsbettingodds_timestamp"))

    op.drop_table("sportsbettingodds")
    with op.batch_alter_table("bookmakermatch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmakermatch_matching_attempts"))

    op.drop_table("bookmakermatch")
    op.drop_table("match")
    # ### end Alembic commands ###
